version = 1

[merge]
automerge_label = "automerge"

[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
versions = ["minor", "patch"]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot", "github-actions"]
