have_fun: false
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    # we disable the summary and code review for the pull request opened event
    # because we want to be sure to trigger it on demand and not automatically.
    help: false
    summary: false
    code_review: true
ignore_patterns: []
