name: "Check open-feature pull request"
on:
  schedule:
    - cron: "0 10 */3 * *"
  workflow_dispatch:

permissions: read-all

jobs:
  check_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      - name: Install dependencies
        working-directory: ./openfeature/ci_scripts
        run: npm install
      - name: Check PRs
        working-directory: ./openfeature/ci_scripts
        run: npm run ci:check_prs_and_open_issue
