name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 8,20 * * *"

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          stale-pr-message: "This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          days-before-issue-stale: 20
          days-before-pr-stale: 45
          days-before-issue-close: 10
          days-before-pr-close: 10
          exempt-issue-labels: "priority:P1,priority:P2,priority:P3,bug,dependencies,roadmap"
          exempt-assignees: thomaspoignant
