name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 8,20 * * *"

permissions: read-all

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f # v10.0.0
        with:
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          stale-pr-message: "This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          days-before-issue-stale: 20
          days-before-pr-stale: 45
          days-before-issue-close: 10
          days-before-pr-close: 10
          exempt-issue-labels: p1,p2,p3,bug,dependencies,roadmap
          exempt-assignees: thomaspoignant
