name: Release Kotlin Provider to Sonatype
on:
  workflow_call:
    inputs:
      version: { type: string, required: false }
    secrets:
      OSSRH_USERNAME: { required: true }
      OSSRH_PASSWORD: { required: true }
      GPG_SIGNING_KEY: { required: true }
      GPG_SIGNING_KEY_PASSWORD: { required: true }
      GPG_SIGNING_KEY_ID: { required: true }

permissions:
  actions: read
  contents: read

jobs:
  kotlin-release:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Gradle and wrapper
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          fingerprint: 9ACC46AB4C1DD2104D5DFB2AFC87955F83FE4262
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | gpg --import
          gpg --passphrase $GPG_SIGNING_KEY_PASSWORD --pinentry-mode=loopback --export-secret-key 83FE4262 > /home/runner/.gnupg/secring.gpg
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Add signing secrets to gradle.properties
        run: |
          mkdir -p ~/.gradle/
          echo "signing.keyId=83FE4262" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=/home/runner/.gnupg/secring.gpg" >> ~/.gradle/gradle.properties
          echo "signing.password=$GPG_SIGNING_KEY_PASSWORD" >> ~/.gradle/gradle.properties
        env:
          GPG_SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
          GPG_SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: 17
          distribution: "zulu"

      - name: Grant Permission for Gradlew to Execute
        working-directory: ./openfeature/providers/kotlin-provider
        run: chmod +x gradlew

      - name: Publish to Sonatype
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        working-directory: ./openfeature/providers/kotlin-provider
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --stacktrace

      - name: Clean up signing secrets
        working-directory: ./openfeature/providers/kotlin-provider
        run: rm ~/.gradle/gradle.properties
