name: "Check all SDK versions and update the documentation"
on:
  schedule:
    - cron: "0 9 * * *"

permissions: read-all

jobs:
  sdk-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: ./website/.ci/go.mod
          check-latest: true
      - run: go run ./website/.ci/sdkVersions.go
      - uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          push_options: "--force"
          commit_message: "docs(website): update SDK versions"
