name: "Check all SDK versions and update the documentation"
on:
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: read

jobs:
  sdk-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: ./website/.ci/go.mod
          check-latest: true
      - run: go run ./website/.ci/sdkVersions.go
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          push_options: "--force"
          commit_message: "docs(website): update SDK versions"
