name: "Check all SDK versions and update the documentation"
on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  sdk-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ./website/.ci/go.mod
          check-latest: true
      - run: go run ./website/.ci/sdkVersions.go
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          push_options: "--force"
          commit_message: "docs(website): update SDK versions"
